### ISSUE TITLE
Application does not start in Starcounter 2.1.177

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#13]
I cannot start the app in Starcounter 2.1.177. 

There are three cryptic error messages in the log:

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.1.177. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.    at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163    at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154    at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 153
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```

```
 ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.1.177. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.    at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163    at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154    at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36    --- End of inner exception stack trace ---
```

```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "C:\www\StarcounterSamples\KitchenSink\bin\Debug\KitchenSink.exe" --outdir="c:\db\Personal\Temp\Default\Default-20160121T101125603\weaver\680264E04044CBEC8A4A0143D6BC67DC84BEEFDC"
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163
   at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154
   at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163
   at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154
   at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---

Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
```

![image](https://cloud.githubusercontent.com/assets/566463/12479125/5926d826-c039-11e5-98ab-536a687c431d.png)

@per-samuelsson any idea?

**Comment by warpech** [comment]
I don't get this problem in current nightly, meaning it is not a problem in current Starcounter anymore. But is there anything I can do to make it work in 2.1.177? I wonder if there is some single thing causing it

**Comment by per-samuelsson** [comment]
> I wonder if there is some single thing causing it

I am too. I'm currently looking through issues from the history to see if can find some clue: https://github.com/Starcounter/Starcounter/search?q=ScErrUnhandledWeaverException&type=Issues. The error you are experiencing is more or less an internal bug IMO.

You have to give me at least a few minutes :clock1030:

**Comment by per-samuelsson** [comment]
Meanwhile, can you test something for me:

Browse to the folder of the `KitchenZink.exe`  and run

```
scweaver --nocache KitchenZink.exe
```

when having 2.1.177 installed to see if that work.

**Comment by warpech** [comment]
Thanks! 

Unfortunately, same problem:

```
C:\www\StarcounterSamples\KitchenSink\bin\Debug>scweaver --nocache KitchenSink.e
xe
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unide
ntified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.Ge
tColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCit
y8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal
.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163
   at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamC
ity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Intern
al.Weaver\ScTransformTask.cs:line 227
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] m
odules)
   at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgen
t\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\Team
City\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeav
er.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, Stri
ng outputDirectory, String cacheDirectory, String fileName, ApplicationArguments
 arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1
\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationA
rguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-21
8\Level1\src\scweaver\Program.cs:line 154
   at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\bu
ildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---
```

In context of the search results linked above: KitchenSink does not use SO (directly nor indirectly). It defines only a single Database class: [TreeItem](https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/BreadcrumbPage.json.cs)

**Comment by per-samuelsson** [comment]
> It defines only a single Database class: TreeItem

None of our applications do anymore, unfortunatelly. You always get all the ones from the installation too, whether you like it our not.

**Comment by per-samuelsson** [comment]
> Unfortunately, same problem:

Argh. Try this then:

```
scweaver --nocache --disableeditionlibraries KitchenZink.exe
```

**Comment by per-samuelsson** [comment]
(What I'm shooting for is that its probably something with all the libraries being pulled in, rather than with your application itself).

**Comment by warpech** [comment]
Spot on! No error with `scweaver --nocache --disableeditionlibraries KitchenZink.exe`

But using just `scweaver`, the app is not listed in Administrator, does not respond to HTTP requests etc. Anything I can do?

**Comment by per-samuelsson** [comment]
> But using just scweaver, the app is not listed in Administrator, does not respond to HTTP requests etc. Anything I can do?

Nah, exactly. Just wanted to first "take a few steps back" to narrow the scope a little. In Starcounter nowadays, you simply can't run a stand-alone application, as you know. You always will get those libraries, whether you like it or not.

FWIW, [this October issue](https://github.com/Starcounter/Starcounter/issues/2997) from @miyconst seem to be more or less the same thing. I'm trying to find out if that bug was fixed in the version you are trying to use (crossing my fingers the case is not so).

**Comment by per-samuelsson** [comment]
Good and bad news: this issue was [fixed](https://github.com/Starcounter/Starcounter/issues/2997#issuecomment-151876759). Bad news: it's not fixed in 2.1.177. :cry:

**Comment by per-samuelsson** [comment]
If you really, really, really know what you are doing, and you absolutely want just that `KitchenZink.exe` to run on 2.1.177, you could go in an rename `%StarcounterBin%\EditionLibraries` and I *think* it should work. You might need to delete the application folder with weaved artifacts first though.

**Comment by per-samuelsson** [comment]
> You might need to delete the application folder with weaved artifacts first though.

That would be this folder in this particular case:

```
c:\db\Personal\Temp\Default\Default-20160121T101125603\weaver\680264E04044CBEC8A4A0143D6BC67DC84BEEFDC
```

**Comment by chrhol** [comment]
> If you really, really, really know what you are doing, and you absolutely want just that KitchenZink.exe to run on 2.1.177, you could go in an rename %StarcounterBin%\EditionLibraries and I think it should work. You might need to delete the application folder with weaved artifacts first though.

You can disable loading the edition libraries in the setting for the database. Just change the property `<LoadEditionLibraries>` to `False` in the database config file.

**Comment by warpech** [comment]
Great, thanks! That's enough for me

**Comment by per-samuelsson** [comment]
> You can disable loading the edition libraries in the setting for the database. Just change the property `<LoadEditionLibraries>` to `False` in the database config file.

Ahh, I forgot that we actually had some of that surfaced (at least to the point of manual XML config). Thanks for pointing that out @chrhol!

If you decide to take that advice up, be sure you restart the database for it to take effect.

**Comment by warpech** [comment]
Actually setting `<LoadEditionLibraries>` to `false` in `C:\db\Personal\Personal.server.config` does not help. Renaming the directory to `EditionLibraries_` helps.

@chrhol can you verify if this is some bug in config reader?

**Comment by warpech** [comment]
This is funny because I can see that `<LoadEditionLibraries>false` prevents Simplified and SO from being weaved. So this is not a bug in config reader.

I guess this is not worthwhile investigating, but it is a bummer. Hopefully we will have a stable release soon.
