### ISSUE TITLE
Remove custom table definitions

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#92]
@un-tone, after the PR #89, KitchenSink defines its own classes for the custom data.

This has a side effect: after starting and stopping KitchenSink, other sample app (Products) is not usable.

Unfortunately, in Starcounter you need the class definition to be loaded in order for use it. For example, Products app sees the products created in KitchenSink, but if KitchenSink is not started, it will produce the below exception ([more info](https://github.com/Starcounter/Starcounter/search?q=ScErrSchemaCodeMismatch&type=Issues&utf8=%E2%9C%93)):

```txt
Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema. CLR Class is not loaded for table KitchenSink.SoftwareProduct
Version: 2.3.0.5512.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
   at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter\Binding\Bindings.cs:line 485
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter\Binding\Bindings.cs:line 353
   at Starcounter.Enumerator.MoveNext() in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter\Mock\Enumerator.cs:line 239
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 479
   at Starcounter.Json.Array_InitializeAfterImplicitConversion(Json parent, TObjArr template) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Class Json\Json.Array.cs:line 85
   at Starcounter.Templates.TArray`1.BoundOrUnboundSet(Json parent, Arr`1 value) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 119
   at Products.ProductListPage.set_Products(Arr`1 value) in c:\www\Products\src\Products\obj\x64\Debug\ViewModels\ViewModels\ProductListPage.json:line 3
   at Products.ProductListPage.RefreshProducts() in c:\www\Products\src\Products\ViewModels\ProductListPage.json.cs:line 11
   at Products.MainHandlers.<>c.<Register>b__0_14() in c:\www\Products\src\Products\Api\MainHandlers.cs:line 119
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at Products.MainHandlers.<>c.<Register>b__0_11() in c:\www\Products\src\Products\Api\MainHandlers.cs:line 92
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
ErrorCode=4177
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4177
More information about this error may be available in the server error log.
```

To fix this, I recommend to either:

1. KitchenSink database classes should be standalone (not extend Simplified classes)
2. KitchenSink should use Simplified classes directly (without extending)

I slightly prefer 1., but the choice is yours.

cc @KmaTTi89

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterSamples/KitchenSink/pull/93

**Comment by warpech** [comment]
Thanks, closing as done
